import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  wrapper: {
    width: '100%',
    maxWidth: 1200,
    marginHorizontal: 'auto',
    padding: 30,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 15,
    shadowOffset: { width: 0, height: 4 },
    elevation: 10,
    color: '#2b86e2',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 30,
    padding: 20,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
  },
  title: {
    fontSize: 28,
    margin: 0,
    color: '#2b86e2',
    fontWeight: '700',
    letterSpacing: 1,
  },
  backButton: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 40,
    fontSize: 16,
    fontWeight: '600',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  backButtonText: {
    color: '#fff', 
    fontWeight: '400',
    fontSize: 14,
    textAlign: 'center',
  },
  
  backButtonHover: {
    backgroundColor: 'rgba(43, 134, 226, 0.1)',
    borderColor: '#4f73f1',
    transform: [{ translateY: -2 }],
  },
  statsSection: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 40,
    padding: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
  },
  stat: {
    alignItems: 'center',
    padding: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
  },
  statHover: {
    transform: [{ translateY: -3 }],
    borderColor: 'rgba(79, 115, 241, 0.3)',
  },
  statTitle: {
    marginBottom: 15,
    color: '#2b86e2',
    fontSize: 16,
    fontWeight: '600',
  },
  statValue: {
    fontSize: 18,
    color: '#4f73f1',
    fontWeight: 'bold',
  },
  favoritesList: {
    flexDirection: 'column',
    gap: 25,
    paddingVertical: 20,
  },
  favoriteCard: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  favoriteCardHover: {
    transform: [{ translateY: -5 }],
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
    borderColor: 'rgba(79, 115, 241, 0.3)',
  },
  bookCover: {
    width: 150,
    height: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    marginRight: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 2,
  },
  bookCoverHover: {
    transform: [{ scale: 1.05 }],
  },
  bookInfo: {
    flex: 1,
    flexDirection: 'column',
  },
  bookTitle: {
    marginBottom: 10,
    fontSize: 18,
    color: '#2b86e2',
    fontWeight: '600',
  },
  bookAuthor: {
    marginBottom: 15,
    color: 'rgba(43, 134, 226, 0.8)',
    fontSize: 14,
  },
  genre: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(79, 115, 241, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(79, 115, 241, 0.3)',
    borderRadius: 20,
    fontSize: 12,
    color: '#4f73f1',
    marginBottom: 15,
  },
  dateAdded: {
    color: 'rgba(43, 134, 226, 0.7)',
    fontSize: 12,
    marginBottom: 15,
    fontStyle: 'italic',
  },
  notesArea: {
    width: '100%',
    minHeight: 100,
    padding: 15,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    color: '#2b86e2',
    marginBottom: 20,
    fontSize: 14,
  },
  notesAreaFocus: {
    borderColor: '#4f73f1',
    shadowColor: '#4f73f1',
    shadowOpacity: 0.6,
    shadowRadius: 8,
  },
  cardActions: {
    flexDirection: 'row',
    gap: 15,
    marginTop: 'auto',
  },
  removeButton: {
    backgroundColor: 'rgba(255, 73, 73, 0.1)',
    color: '#ff4949',
    borderWidth: 2,
    borderColor: 'rgba(255, 73, 73, 0.3)',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 40,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  removeButtonHover: {
    backgroundColor: 'rgba(255, 73, 73, 0.2)',
    transform: [{ translateY: -2 }],
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
  readButton: {
    backgroundColor: '#4f73f1',
    color: 'white',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 40,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  readButtonHover: {
    backgroundColor: '#405bb6',
    transform: [{ translateY: -2 }],
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 5,
  },
});

export default styles;
