import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  wrapper: {
    width: 420, 
    backgroundColor: 'transparent',
    borderColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 2,
    borderRadius: 12, 
    paddingVertical: 30,
    paddingHorizontal: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 15, 
    margin: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between', 
    alignItems: 'center', 
    paddingHorizontal: 20,
    paddingVertical: 10, 
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
    width: '100%', 
  },
  title: {
    fontSize: 32,
    color: '#2b86e2',
    fontWeight: '700',
    letterSpacing: 1,
    textAlign: 'left',
  },
  navbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  navButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginHorizontal: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  navButtonText: {
    color: '#2b86e2',
    fontSize: 16,
    fontWeight: '600',
  },
  content: {
    padding: 20,
  },
  featuredSection: {
    marginBottom: 40,
  },
  sectionTitle: {
    fontSize: 24,
    marginBottom: 20,
    color: '#2b86e2',
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  bookGrid: {
    flexWrap: 'wrap', 
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 25,
  },
  bookCard: {
    width: '45%', 
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 20,
    alignItems: 'center',
    marginBottom: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  bookCardHover: {
    transform: [{ translateY: -5 }],
    borderColor: 'rgba(79, 115, 241, 0.3)',
    shadowRadius: 8,
  },
  bookCover: {
    width: 140,
    height: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    marginBottom: 15,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  bookTitle: {
    fontSize: 18,
    color: '#2b86e2',
    fontWeight: '600',
    marginBottom: 5,
    textAlign: 'center',
  },
  bookAuthor: {
    fontSize: 16,
    color: 'rgba(43, 134, 226, 0.8)',
    textAlign: 'center',
  },
  quickActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 40,
    gap: 20, 
  },
  actionButton: {
    backgroundColor: '#4f73f1',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    alignItems: 'center',
  },
  actionButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },
  actionButtonHover: {
    backgroundColor: '#405bb6',
    transform: [{ translateY: -2 }],
    shadowRadius: 8,
  },
});

export default styles;
